edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
indent_style = "Block"
fn_single_line = false
fn_args_layout = "Tall"
where_single_line = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
normalize_comments = true
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 80
normalize_doc_attributes = true
license_template_path = ""
license_template = ""
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 35
enum_variant_width = 35
single_line_if_else_max_width = 50
trailing_comma = "Vertical"
match_block_trailing_comma = false
match_arm_blocks = true
force_multiline_blocks = false
fn_args_paren_newline = true
closure_indent_width = 4
closure_indent_style = "Visual"
closure_brace_style = "SameLineWhere"
struct_lit_brace_style = "SameLineWhere"
struct_lit_multiline_style = "PreferSingle"
struct_lit_indent_style = "Visual"
struct_lit_indent = 4
array_width = 60
array_indent = 4
array_horizontal_layout_threshold = 8
array_layout = "Vertical"
array_indent_style = "Block"